const { Router } = require("express");
const categoriesController = require("../../controllers/categoriesController");
const router = Router();
router.post("/marque", categoriesController.createMarque);
router.post("/gamme", categoriesController.createGamme);
router.post("/category", categoriesController.createCategory);
router.get("/marque", categoriesController.getAllMarque);
router.get("/gamme", categoriesController.getAllGamme);
router.get("/category", categoriesController.getAllCategory);
module.exports = router;
